### ISSUE TITLE
線形代数

### ISSUE THREAD

**Issue by nzw0301** [KlisMathClub/wanted#1]
固有値とか必要っすもんね

**Comment by himkt** [comment]
はい..
何か一つの教材やるべきでしょうか

**Comment by nzw0301** [comment]
あったほうが体系的にできていい感じが

**Comment by nzw0301** [comment]
研究室に一冊余ってるのがあります
http://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E7%B7%9A%E5%BD%A2%E4%BB%A3%E6%95%B0-%E5%B9%B3%E5%B2%A1-%E5%92%8C%E5%B9%B8/dp/4274065782

**Comment by himkt** [comment]
一応、http://www.amazon.co.jp/%E9%95%B7%E5%B2%A1%E4%BA%AE%E4%BB%8B%E7%B7%9A%E5%9E%8B%E4%BB%A3%E6%95%B0%E5%85%A5%E9%96%80%E8%AC%9B%E7%BE%A9%E2%80%95%E7%8F%BE%E4%BB%A3%E6%95%B0%E5%AD%A6%E3%81%AE%E2%80%9C%E6%8A%80%E6%B3%95%E2%80%9D%E3%81%A8%E2%80%9C%E5%BF%83%E2%80%9D-%E9%95%B7%E5%B2%A1-%E4%BA%AE%E4%BB%8B/dp/4489020821/ref=sr_1_1?ie=UTF8&qid=1435058324&sr=8-1&keywords=%E7%B7%9A%E5%BD%A2%E4%BB%A3%E6%95%B0%E5%85%A5%E9%96%80%E8%AC%9B%E7%BE%A9
を持ってはいます。プログラミングのための〜のほうが良さそうならそちらを買ってやります
